spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/hackday/devcenter-bot;AUTO_SERVER=TRUE;MODE=MySQL
    continue-on-error: true

github:
  user: kkyehit
  repo: egit-github-test
  #token: OS환경변수나 -Dsocial.github.token 값 등으로 설정

logging:
  level:
    org.springframework.jdbc.core: TRACE
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE


