spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/hackday/devcenter-bot;AUTO_SERVER=TRUE;MODE=MySQL
    continue-on-error: true

  social:
    github:
      user: kkyehit
      password:
      repo: egit-github-test
      token:

logging:
  level:
    org.springframework.jdbc.core: TRACE
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE


