spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/hackday/devcenter-bot;AUTO_SERVER=TRUE;MODE=MySQL
    continue-on-error: true

  social:
    github:
      user: kkyehit
      repo: egit-github-test
      token: ee8e2420581221dc46085c8e4c156afb8cb63cb7

logging:
  level:
    org.springframework.jdbc.core: TRACE
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE

id: rp01020113994@gmail.com
password: gosemvhs3#
token: ee8e2420581221dc46085c8e4c156afb8cb63cb7
